name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: akhileshns/heroku-deploy@v1
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
